import ForgetPassword from "./ForgetPassword";
import Login from "./Login";
import MainScreen from "./MainScreen";
import NewPasswordOnWay from "./NewPassword";
import SignUpOne from "./SignUpOne";
import SignUpEmailVerificationSent from "./SignUpEmailVerificationSent";
import ResetPassword from "./ResetPassword";
import EmailVerification from "./EmailVerification";
import Profile from "./Profile";
import Support from "./Support";
import ResetPasswordConfirmation from "./ResetPasswordConfirmation/ResetPasswordConfirmation";
export {ForgetPassword, Login, MainScreen, NewPasswordOnWay, SignUpOne, SignUpEmailVerificationSent, ResetPassword, EmailVerification, Profile, Support, ResetPasswordConfirmation};