export const Url={
    signUp:"auth/users/",
    loginUrl:"auth/login/",
    forgetPass:"auth/users/reset_password/",
    resendMail:"auth/users/resend_activation/",
    emailVerification:"auth/users/activation/",
    resetPassword:"auth/users/reset_password_confirm/",
    meApi:"api/operator/me",
    connectRobo:"api/operator/me/",
    robotModes:"api/operator/me/?operator_status=",
    disconnectRobot:"api/operator/me/?status=",
    operatorResponse:"api/operator/operator_response/",
    motorStatus:"api/operator/setRobotCommands/?status=",
    rideEnd:"api/operator/tripend/",
}